In [3]:
import pandas as pd

In [8]:
df = pd.read_csv("us_customer_data 1.csv")
df1 = pd.read_csv("transaction_data.csv")

In [9]:
df.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status
0,1,Michelle Kidd,vayala@example.net,619-723-4258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold
1,2,Brad Newton,taylorcatherine@example.net,537-674-1158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver
2,3,Larry Torres,dsanchez@example.net,810-256-4505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze
3,4,Kimberly Price,jessicaknight@example.com,423-222-9779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold
4,5,Matthew Phillips,qwilliams@example.com,220-763-3522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold

In [11]:
df1.head(5)

,transaction_id,customer_id,amount,transaction_date,product_category,payment_method,store_location
0,1,565,2992.47,2025-03-10 01:20:54,Sports,Debit Card,New York
1,2,323,2041.87,2025-01-02 15:24:19,Clothing,Cash,New York
2,3,398,107.35,2025-02-16 03:49:01,Beauty,Debit Card,Online
3,4,19,NaN,2025-04-30 15:26:23,Sports,Debit Card,Los Angeles
4,5,547,3063.28,2025-06-14 04:28:53,Clothing,PayPal,Los Angeles

In [12]:
df.describe()

       customer_id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1000 non-null   int64
 1   name               1000 non-null   object
 2   email              950 non-null    object
 3   phone              984 non-null    object
 4   address            1000 non-null   object
 5   registration_date  1000 non-null   object
 6   loyalty_status     1000 non-null   object
dtypes: int64(1), object(6)
memory usage: 54.8+ KB

In [14]:
dfnew = pd.merge(df,df1,on='customer_id',how = 'outer')

In [15]:
dfnew.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,619-723-4258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.57,2025-04-19 14:46:00,Home,Credit Card,New York
1,2,Brad Newton,taylorcatherine@example.net,537-674-1158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Larry Torres,dsanchez@example.net,810-256-4505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Kimberly Price,jessicaknight@example.com,423-222-9779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.09,2025-04-28 04:34:07,Beauty,PayPal,Chicago
4,5,Matthew Phillips,qwilliams@example.com,220-763-3522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.52,2025-02-03 14:59:13,Sports,PayPal,Online

In [16]:
dfnew.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1348    False
1349    False
1350    False
1351    False
1352    False
Length: 1353, dtype: bool

In [17]:
dfnew.duplicated().sum()

np.int64(0)

In [18]:
dfnew.isnull().sum()

customer_id            0
name                   0
email                 56
phone                 24
address                0
registration_date      0
loyalty_status         0
transaction_id       353
amount               403
transaction_date     353
product_category     353
payment_method       353
store_location       353
dtype: int64

In [20]:
dfnew.loc[dfnew['email'].isnull(),'email'] = dfnew['name'].str.lower() + '@example.com'

In [21]:
dfnew.head(50)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,619-723-4258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.57,2025-04-19 14:46:00,Home,Credit Card,New York
1,2,Brad Newton,taylorcatherine@example.net,537-674-1158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Larry Torres,dsanchez@example.net,810-256-4505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Kimberly Price,jessicaknight@example.com,423-222-9779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.09,2025-04-28 04:34:07,Beauty,PayPal,Chicago
4,5,Matthew Phillips,qwilliams@example.com,220-763-3522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.52,2025-02-03 14:59:13,Sports,PayPal,Online
5,6,Darrell Gallagher DVM,larryharris@example.org,379-950-3695,"19887 Brandon Bridge, New Rebecca, MA 94947",03-03-2025,Bronze,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Louis Miller,patriciaelliott@example.org,198-862-7105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,470.0,3241.66,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles
7,7,Louis Miller,patriciaelliott@example.org,198-862-7105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,857.0,697.57,2025-06-13 12:03:42,Beauty,Debit Card,Chicago
8,8,Melissa Galloway MD,watsonbenjamin@example.net,548-549-9586,"209 Steven Oval Apt. 022, Mollyhaven, NC 10211",06-10-2023,Bronze,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Matthew Harvey,bgaines@example.net,581-144-7338,"60123 Davis Ford, Mistychester, WA 69400",31-10-2024,Silver,300.0,918.34,2025-05-07 20:01:01,Electronics,PayPal,Miami
10,10,Rachel White,whitemichael@example.org,410-729-9740,"6182 Brown Mountain, South Gary, IL 29016",25-02-2024,Bronze,173.0,3456.05,2025-04-15 19:26:48,Home,Debit Card,Online
11,10,Rachel White,whitemichael@example.org,410-729-9740,"6182 Brown Mountain, South Gary, IL 29016",25-02-2024,Bronze,548.0,2954.52,2025-05-21 22:54:54,Sports,Debit Card,Miami
12,10,Rachel White,whitemichael@example.org,410-729-9740,"6182 Brown Mountain, South Gary, IL 29016",25-02-2024,Bronze,831.0,220.35,2025-05-21 17:47:53,Sports,PayPal,Los Angeles
13,11,Nicole Yang,archerheather@example.org,589-638-7173,"923 Emily Mills Apt. 281, Port Roy, WI 03921",08-03-2025,Bronze,NaN,NaN,NaN,NaN,NaN,NaN
14,12,Christine Delgado,yfarrell@example.net,310-834-9008,"PSC 4025, Box 2078, APO AA 61121",18-04-2024,Bronze,126.0,3696.64,2025-02-15 19:59:56,Beauty,Cash,Online
15,12,Christine Delgado,yfarrell@example.net,310-834-9008,"PSC 4025, Box 2078, APO AA 61121",18-04-2024,Bronze,560.0,NaN,2025-02-08 02:57:55,Beauty,Debit Card,Miami
16,13,Joseph Brennan,khernandez@example.com,486-789-1647,"8890 Keller Hills, North Paul, FM 64749",28-04-2024,Gold,301.0,NaN,2025-03-18 04:40:03,Beauty,Debit Card,Chicago
17,13,Joseph Brennan,khernandez@example.com,486-789-1647,"8890 Keller Hills, North Paul, FM 64749",28-04-2024,Gold,967.0,631.85,2025-02-18 17:30:32,Home,Cash,Online
18,14,Eric Thomas,spencer75@example.com,434-130-5478,"352 Joel Extension Suite 962, New Anthony, CO ...",09-05-2024,Bronze,NaN,NaN,NaN,NaN,NaN,NaN
19,15,Laura Perez,sdavid@example.com,319-310-5560,"1518 Green Locks Suite 348, New Brent, FM 51849",04-12-2024,Gold,504.0,3194.72,2025-06-01 14:13:06,Beauty,Debit Card,Online
20,16,Erin Matthews,uhunter@example.net,480-780-3711,"67623 Morgan Hollow, Hillshire, IL 78665",12-11-2023,Bronze,531.0,322.34,2025-04-05 11:19:25,Clothing,Debit Card,Los Angeles
21,16,Erin Matthews,uhunter@example.net,480-780-3711,"67623 Morgan Hollow, Hillshire, IL 78665",12-11-2023,Bronze,635.0,492.19,2025-01-23 18:39:00,Clothing,Cash,Miami
22,17,Melissa Alvarado,parkjohn@example.net,411-857-4974,"USNS Austin, FPO AP 52643",24-06-2024,Gold,116.0,404.66,2025-05-15 09:16:08,Home,Debit Card,New York
23,17,Melissa Alvarado,parkjohn@example.net,411-857-4974,"USNS Austin, FPO AP 52643",24-06-2024,Gold,374.0,2445.23,2025-02-18 22:07:41,Home,Credit Card,Chicago
24,17,Melissa Alvarado,parkjohn@example.net,411-857-4974,"USNS Austin, FPO AP 52643",24-06-2024,Gold,681.0,4752.12,2025-05-31 10:50:45,Sports,Cash,Miami
25,18,Mr. Ernest Dunn,kelseybrown@example.net,687-543-7471,"3112 Lydia Freeway Suite 927, South Susan, RI ...",27-01-2025,Gold,570.0,2929.47,2025-03-18 13:34:29,Beauty,Credit Card,Miami
26,19,David Johnson,marynelson@example.org,244-439-2274,"992 Harris Pines Suite 049, North Marychester,...",21-02-2025,Silver,4.0,NaN,2025-04-30 15:26:23,Sports,Debit Card,Los Angeles
27,19,David Johnson,marynelson@example.org,244-439-2274,"992 Harris Pines Suite 049, North Marychester,...",21-02-2025,Silver,99.0,4361.19,2025-05-27 16:17:17,Electronics,Credit Card,Chicago
28,19,David Johnson,marynelson@example.org,244-439-2274,"992 Harris Pines Suite 049, North Marychester,...",21-02-2025,Silver,546.0,1600.94,2025-03-24 15:39:10,Beauty,Debit Card,Online
29,20,Wayne Morales,qwilliams@example.com,875-559-3832,"15344 Hill Pike, Matthewport, FL 45434",22-02-2025,Gold,195.0,746.43,2025-04-02 02:14:27,Home,PayPal,Miami
30,20,Wayne Morales,qwilliams@example.com,875-559-3832,"15344 Hill Pike, Matthewport, FL 45434",22-02-2025,Gold,291.0,3402.30,2025-03-24 02:17:33,Electronics,PayPal,Miami
31,20,Wayne Morales,qwilliams@example.com,875-559-3832,"15344 Hill Pike, Matthewport, FL 45434",22-02-2025,Gold,874.0,3934.82,2025-05-04 10:16:59,Sports,Credit Card,Online
32,21,Michael Vincent,jonesjeffrey@example.com,685-935-4111,"455 Moore Orchard, New Richardhaven, RI 42023",13-06-2024,Silver,176.0,4674.53,2025-02-25 15:55:18,Clothing,Credit Card,Miami
33,22,Tammie Mcgee,nsullivan@example.com,176-840-2659,"6371 Long Path Apt. 940, South Anthonyton, MT ...",24-10-2024,Silver,721.0,640.83,2025-05-04 03:33:13,Sports,Cash,Los Angeles
34,23,Marisa Martinez,zward@example.org,221-609-1291,"5029 Wall Mountain Suite 847, New Chelseabury,...",29-03-2025,Bronze,442.0,1908.49,2025-04-21 01:10:46,Beauty,Debit Card,Online
35,24,Crystal Peterson,taylorcharles@example.com,430-711-1833,"Unit 5741 Box 1124, DPO AA 18219",07-08-2023,Bronze,133.0,979.81,2025-06-13 05:19:21,Electronics,PayPal,Online
36,24,Crystal Peterson,taylorcharles@example.com,430-711-1833,"Unit 5741 Box 1124, DPO AA 18219",07-08-2023,Bronze,141.0,1164.89,2025-06-05 09:17:17,Clothing,Debit Card,Chicago
37,24,Crystal Peterson,taylorcharles@example.com,430-711-1833,"Unit 5741 Box 1124, DPO AA 18219",07-08-2023,Bronze,717.0,4292.90,2025-03-18 08:24:05,Home,Cash,Los Angeles
38,25,Jeremy Alexander,smithkevin@example.com,119-969-9309,"1520 Reid Turnpike, Clarkville, CA 39102",13-06-2025,Silver,493.0,591.95,2025-05-13 06:44:39,Beauty,Debit Card,Online
39,26,James Graham,chawkins@example.net,997-656-7695,"2809 Young Squares, Lisaside, VA 53732",10-03-2024,Gold,868.0,3378.58,2025-04-27 11:24:04,Clothing,Debit Card,Los Angeles
40,27,William Morrison,browningdavid@example.org,486-676-8923,"76577 Keith Falls, West Melissashire, NC 55275",01-08-2024,Gold,214.0,2887.52,2025-05-15 08:47:35,Clothing,Debit Card,Chicago
41,27,William Morrison,browningdavid@example.org,486-676-8923,"76577 Keith Falls, West Melissashire, NC 55275",01-08-2024,Gold,753.0,3558.59,2025-04-25 08:18:22,Electronics,PayPal,Miami
42,27,William Morrison,browningdavid@example.org,486-676-8923,"76577 Keith Falls, West Melissashire, NC 55275",01-08-2024,Gold,813.0,2468.38,2025-05-16 04:49:59,Home,PayPal,Los Angeles
43,28,Brandon Hall,brandon hall@example.com,974-123-3048,"8143 Robert Cove Apt. 103, Sanchezport, CO 78231",07-04-2024,Gold,210.0,2404.43,2025-05-11 16:03:42,Clothing,Credit Card,Chicago
44,29,Morgan Wilson,michelle12@example.net,258-480-2466,"05880 Hudson Row, Jessefurt, KS 54128",04-11-2024,Silver,NaN,NaN,NaN,NaN,NaN,NaN
45,30,Heather Hill,qwillis@example.com,442-456-8115,"4339 Brown Crescent, Lambchester, SD 62832",15-12-2024,Silver,946.0,1252.53,2025-06-01 10:04:29,Home,Cash,Miami
46,31,Louis Beasley,bjones@example.net,234-311-3270,"71975 Smith Drive Suite 746, Bairdmouth, MP 70886",18-09-2023,Bronze,905.0,258.16,2025-05-28 23:35:33,Sports,Credit Card,Miami
47,32,Julie Shelton,ryanpatel@example.net,307-103-5146,"USNS Brown, FPO AP 55711",02-12-2024,Gold,70.0,1272.21,2025-04-03 07:26:00,Sports,Debit Card,Miami
48,32,Julie Shelton,ryanpatel@example.net,307-103-5146,"USNS Brown, FPO AP 55711",02-12-2024,Gold,469.0,4664.71,2025-05-06 10:40:47,Sports,PayPal,Los Angeles
49,33,Erin Stephens,kyle83@example.com,649-443-8577,"5911 Amy Creek Suite 329, Michaelside, CO 25722",02-08-2024,Silver,137.0,4934.62,2025-03-28 19:03:18,Electronics,Cash,Online

In [22]:
dfnew.isnull().sum()

customer_id            0
name                   0
email                  0
phone                 24
address                0
registration_date      0
loyalty_status         0
transaction_id       353
amount               403
transaction_date     353
product_category     353
payment_method       353
store_location       353
dtype: int64

In [23]:
dfnew.loc[dfnew['phone'].isnull(),'phone'] = 'Not Available'

In [24]:
dfnew.isnull().sum()

customer_id            0
name                   0
email                  0
phone                  0
address                0
registration_date      0
loyalty_status         0
transaction_id       353
amount               403
transaction_date     353
product_category     353
payment_method       353
store_location       353
dtype: int64

In [29]:
dfnew.loc[dfnew['transaction_id'].isnull(),'transaction_id'] = 'Not Available'
dfnew.loc[dfnew['transaction_date'].isnull(),'transaction_date'] = 'Not Available'
dfnew.loc[dfnew['product_category'].isnull(),'product_category'] = 'Not Available'

In [33]:
dfnew.loc[dfnew['payment_method'].isnull(),'payment_method'] = 'Not Available'
dfnew.loc[dfnew['store_location'].isnull(),'store_location'] = 'Not Available'

In [34]:
dfnew.isnull().sum()

customer_id             0
name                    0
email                   0
phone                   0
address                 0
registration_date       0
loyalty_status          0
transaction_id          0
amount                403
transaction_date        0
product_category        0
payment_method          0
store_location          0
store_location       1000
dtype: int64

In [35]:
dfnew.dropna(dfnew['store_location '].isull(), inplace=True)

AttributeError: 'Series' object has no attribute 'isull'

In [36]:
dfnew = dfnew.drop('store_location ', axis=1)

In [37]:
dfnew.isnull().sum()

customer_id            0
name                   0
email                  0
phone                  0
address                0
registration_date      0
loyalty_status         0
transaction_id         0
amount               403
transaction_date       0
product_category       0
payment_method         0
store_location         0
dtype: int64

In [38]:
dfnew.loc[dfnew['amount'].isnull(),'amount'] = dfnew['amount'].mean()

In [39]:
dfnew.isnull().sum()

customer_id          0
name                 0
email                0
phone                0
address              0
registration_date    0
loyalty_status       0
transaction_id       0
amount               0
transaction_date     0
product_category     0
payment_method       0
store_location       0
dtype: int64

In [41]:
dfnew.head(10)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,619-723-4258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.570000,2025-04-19 14:46:00,Home,Credit Card,New York
1,2,Brad Newton,taylorcatherine@example.net,537-674-1158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
2,3,Larry Torres,dsanchez@example.net,810-256-4505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
3,4,Kimberly Price,jessicaknight@example.com,423-222-9779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.090000,2025-04-28 04:34:07,Beauty,PayPal,Chicago
4,5,Matthew Phillips,qwilliams@example.com,220-763-3522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.520000,2025-02-03 14:59:13,Sports,PayPal,Online
5,6,Darrell Gallagher DVM,larryharris@example.org,379-950-3695,"19887 Brandon Bridge, New Rebecca, MA 94947",03-03-2025,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
6,7,Louis Miller,patriciaelliott@example.org,198-862-7105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,470.0,3241.660000,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles
7,7,Louis Miller,patriciaelliott@example.org,198-862-7105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,857.0,697.570000,2025-06-13 12:03:42,Beauty,Debit Card,Chicago
8,8,Melissa Galloway MD,watsonbenjamin@example.net,548-549-9586,"209 Steven Oval Apt. 022, Mollyhaven, NC 10211",06-10-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
9,9,Matthew Harvey,bgaines@example.net,581-144-7338,"60123 Davis Ford, Mistychester, WA 69400",31-10-2024,Silver,300.0,918.340000,2025-05-07 20:01:01,Electronics,PayPal,Miami

In [44]:
dfnew['phone'] = dfnew['phone'].str.replace(r"[^0-9]", "", regex = True)

In [45]:
dfnew.head(10)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location
0,1,Michelle Kidd,vayala@example.net,6197234258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.570000,2025-04-19 14:46:00,Home,Credit Card,New York
1,2,Brad Newton,taylorcatherine@example.net,5376741158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
2,3,Larry Torres,dsanchez@example.net,8102564505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
3,4,Kimberly Price,jessicaknight@example.com,4232229779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.090000,2025-04-28 04:34:07,Beauty,PayPal,Chicago
4,5,Matthew Phillips,qwilliams@example.com,2207633522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.520000,2025-02-03 14:59:13,Sports,PayPal,Online
5,6,Darrell Gallagher DVM,larryharris@example.org,3799503695,"19887 Brandon Bridge, New Rebecca, MA 94947",03-03-2025,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
6,7,Louis Miller,patriciaelliott@example.org,1988627105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,470.0,3241.660000,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles
7,7,Louis Miller,patriciaelliott@example.org,1988627105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,857.0,697.570000,2025-06-13 12:03:42,Beauty,Debit Card,Chicago
8,8,Melissa Galloway MD,watsonbenjamin@example.net,5485499586,"209 Steven Oval Apt. 022, Mollyhaven, NC 10211",06-10-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available
9,9,Matthew Harvey,bgaines@example.net,5811447338,"60123 Davis Ford, Mistychester, WA 69400",31-10-2024,Silver,300.0,918.340000,2025-05-07 20:01:01,Electronics,PayPal,Miami

In [46]:
dfnew.isnull().sum()

customer_id          0
name                 0
email                0
phone                0
address              0
registration_date    0
loyalty_status       0
transaction_id       0
amount               0
transaction_date     0
product_category     0
payment_method       0
store_location       0
dtype: int64

In [52]:
dfnew['country_code']= dfnew['address'].str[-8:-6]

In [50]:
dfnew = dfnew.drop('country_code',axis =1)

In [53]:
dfnew.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location,country_code
0,1,Michelle Kidd,vayala@example.net,6197234258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.570000,2025-04-19 14:46:00,Home,Credit Card,New York,AE
1,2,Brad Newton,taylorcatherine@example.net,5376741158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,MT
2,3,Larry Torres,dsanchez@example.net,8102564505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,UT
3,4,Kimberly Price,jessicaknight@example.com,4232229779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.090000,2025-04-28 04:34:07,Beauty,PayPal,Chicago,CA
4,5,Matthew Phillips,qwilliams@example.com,2207633522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.520000,2025-02-03 14:59:13,Sports,PayPal,Online,OR

In [59]:
dfx = pd.read_csv('countrycodes.csv',engine ='python',on_bad_lines='skip')

In [64]:
dfx.columns = dfx.columns.str.strip()

In [67]:
dfx = dfx.drop('Country', axis=1)

In [68]:
dfx = dfx.rename(columns={'ISO2': 'country_code'})

In [69]:
dfx.head(5)

  country_code CallingCode
0           AF          93
1           AL         355
2           DZ         213
3           AD         376
4           AO         244

In [70]:
dfnew = pd.merge(dfnew,dfx,on ='country_code',how='left')

In [71]:
dfnew.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location,country_code,CallingCode
0,1,Michelle Kidd,vayala@example.net,6197234258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.570000,2025-04-19 14:46:00,Home,Credit Card,New York,AE,971
1,2,Brad Newton,taylorcatherine@example.net,5376741158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,MT,356
2,3,Larry Torres,dsanchez@example.net,8102564505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,UT,NaN
3,4,Kimberly Price,jessicaknight@example.com,4232229779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.090000,2025-04-28 04:34:07,Beauty,PayPal,Chicago,CA,1
4,5,Matthew Phillips,qwilliams@example.com,2207633522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.520000,2025-02-03 14:59:13,Sports,PayPal,Online,OR,NaN

In [72]:
dfnew.loc[dfnew['CallingCode'].isnull(),'CallingCode']='1'

In [74]:
dfnew.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location,country_code,CallingCode
0,1,Michelle Kidd,vayala@example.net,6197234258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.570000,2025-04-19 14:46:00,Home,Credit Card,New York,AE,971
1,2,Brad Newton,taylorcatherine@example.net,5376741158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,MT,356
2,3,Larry Torres,dsanchez@example.net,8102564505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,UT,1
3,4,Kimberly Price,jessicaknight@example.com,4232229779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.090000,2025-04-28 04:34:07,Beauty,PayPal,Chicago,CA,1
4,5,Matthew Phillips,qwilliams@example.com,2207633522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.520000,2025-02-03 14:59:13,Sports,PayPal,Online,OR,1

In [76]:
dfnew.loc[dfnew['phone'].notna(),'phone']= "+" + dfnew['CallingCode'] + " " + dfnew['phone']

In [77]:
dfnew.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location,country_code,CallingCode
0,1,Michelle Kidd,vayala@example.net,+971 6197234258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.570000,2025-04-19 14:46:00,Home,Credit Card,New York,AE,971
1,2,Brad Newton,taylorcatherine@example.net,+356 5376741158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,MT,356
2,3,Larry Torres,dsanchez@example.net,+1 8102564505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze,Not Available,2532.550126,Not Available,Not Available,Not Available,Not Available,UT,1
3,4,Kimberly Price,jessicaknight@example.com,+1 4232229779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold,427.0,1787.090000,2025-04-28 04:34:07,Beauty,PayPal,Chicago,CA,1
4,5,Matthew Phillips,qwilliams@example.com,+1 2207633522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold,452.0,1983.520000,2025-02-03 14:59:13,Sports,PayPal,Online,OR,1

In [78]:
df.loc[567]

customer_id                                                     568
name                                                   Erin Richard
email                                      juliagardner@example.net
phone                                                  768-837-5244
address              0505 Robert Greens, Port Heatherstad, KY 47124
registration_date                                        13-11-2024
loyalty_status                                               Bronze
Name: 567, dtype: object

In [79]:
df.head(600)

,customer_id,name,email,phone,address,registration_date,loyalty_status
0,1,Michelle Kidd,vayala@example.net,619-723-4258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold
1,2,Brad Newton,taylorcatherine@example.net,537-674-1158,"38783 Oliver Street, West Kristenborough, MT 9...",13-07-2023,Silver
2,3,Larry Torres,dsanchez@example.net,810-256-4505,"6845 Steele Turnpike, West Erikabury, UT 37487",18-08-2023,Bronze
3,4,Kimberly Price,jessicaknight@example.com,423-222-9779,"1631 Alexis Meadows, Lake Amanda, CA 75179",08-12-2024,Gold
4,5,Matthew Phillips,qwilliams@example.com,220-763-3522,"2274 Williams Heights Suite 895, Andersonhaven...",03-02-2024,Gold
...,...,...,...,...,...,...,...
595,596,Carol Shaffer,burnsscott@example.org,772-782-9223,"81324 John Walk, Alanchester, PA 20064",23-10-2023,Bronze
596,597,Autumn Jordan,hjohnson@example.com,131-995-2389,"63828 Parsons Estate, Martinburgh, DC 64106",04-05-2024,Gold
597,598,Melissa Adams,aimee17@example.net,786-827-2392,"662 Kimberly Row Suite 993, Rebeccaborough, MT...",18-10-2023,Gold
598,599,Jeremy Sparks,qwillis@example.com,602-942-4637,"5929 Mary Drives Apt. 763, Derrickmouth, AS 94889",11-07-2024,Bronze
599,600,Jeffrey Dean,brentsullivan@example.net,422-804-7399,"2193 Charles Locks Apt. 483, Lake Kristen, WI ...",25-06-2023,Bronze

In [84]:
print(dfnew.head(600).to_string(index=False))

 customer_id                    name                          email           phone                                                        address registration_date loyalty_status transaction_id      amount    transaction_date product_category payment_method store_location country_code CallingCode
           1           Michelle Kidd             vayala@example.net +971 6197234258                                    USNS Santiago, FPO AE 80872        25-01-2025           Gold            8.0 2652.570000 2025-04-19 14:46:00             Home    Credit Card       New York           AE         971
           2             Brad Newton    taylorcatherine@example.net +356 5376741158             38783 Oliver Street, West Kristenborough, MT 99752        13-07-2023         Silver  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           MT         356
           3            Larry Torres           dsanchez@example.net   +1 8102564505                 6845 Steele Turnpike, West Erikabury, UT 37487        18-08-2023         Bronze  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           UT           1
           4          Kimberly Price      jessicaknight@example.com   +1 4232229779                     1631 Alexis Meadows, Lake Amanda, CA 75179        08-12-2024           Gold          427.0 1787.090000 2025-04-28 04:34:07           Beauty         PayPal        Chicago           CA           1
           5        Matthew Phillips          qwilliams@example.com   +1 2207633522       2274 Williams Heights Suite 895, Andersonhaven, OR 80565        03-02-2024           Gold          452.0 1983.520000 2025-02-03 14:59:13           Sports         PayPal         Online           OR           1
           6   Darrell Gallagher DVM        larryharris@example.org +212 3799503695                    19887 Brandon Bridge, New Rebecca, MA 94947        03-03-2025         Bronze  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           MA         212
           7            Louis Miller    patriciaelliott@example.org   +1 1988627105                    02590 Marshall Well, Sheppardland, CT 88067        30-09-2024           Gold          470.0 3241.660000 2025-05-15 15:17:05      Electronics         PayPal    Los Angeles           CT           1
           7            Louis Miller    patriciaelliott@example.org   +1 1988627105                    02590 Marshall Well, Sheppardland, CT 88067        30-09-2024           Gold          857.0  697.570000 2025-06-13 12:03:42           Beauty     Debit Card        Chicago           CT           1
           8     Melissa Galloway MD     watsonbenjamin@example.net   +1 5485499586                 209 Steven Oval Apt. 022, Mollyhaven, NC 10211        06-10-2023         Bronze  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           NC           1
           9          Matthew Harvey            bgaines@example.net   +1 5811447338                       60123 Davis Ford, Mistychester, WA 69400        31-10-2024         Silver          300.0  918.340000 2025-05-07 20:01:01      Electronics         PayPal          Miami           WA           1
          10            Rachel White       whitemichael@example.org +972 4107299740                      6182 Brown Mountain, South Gary, IL 29016        25-02-2024         Bronze          173.0 3456.050000 2025-04-15 19:26:48             Home     Debit Card         Online           IL         972
          10            Rachel White       whitemichael@example.org +972 4107299740                      6182 Brown Mountain, South Gary, IL 29016        25-02-2024         Bronze          548.0 2954.520000 2025-05-21 22:54:54           Sports     Debit Card          Miami           IL         972
          10            Rachel White       whitemichael@example.org +972 4107299740                      6182 Brown Mountain, South Gary, IL 29016        25-02-2024         Bronze          831.0  220.350000 2025-05-21 17:47:53           Sports         PayPal    Los Angeles           IL         972
          11             Nicole Yang      archerheather@example.org   +1 5896387173                   923 Emily Mills Apt. 281, Port Roy, WI 03921        08-03-2025         Bronze  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           WI           1
          12       Christine Delgado           yfarrell@example.net   +1 3108349008                               PSC 4025, Box 2078, APO AA 61121        18-04-2024         Bronze          126.0 3696.640000 2025-02-15 19:59:56           Beauty           Cash         Online           AA           1
          12       Christine Delgado           yfarrell@example.net   +1 3108349008                               PSC 4025, Box 2078, APO AA 61121        18-04-2024         Bronze          560.0 2532.550126 2025-02-08 02:57:55           Beauty     Debit Card          Miami           AA           1
          13          Joseph Brennan         khernandez@example.com +691 4867891647                        8890 Keller Hills, North Paul, FM 64749        28-04-2024           Gold          301.0 2532.550126 2025-03-18 04:40:03           Beauty     Debit Card        Chicago           FM         691
          13          Joseph Brennan         khernandez@example.com +691 4867891647                        8890 Keller Hills, North Paul, FM 64749        28-04-2024           Gold          967.0  631.850000 2025-02-18 17:30:32             Home           Cash         Online           FM         691
          14             Eric Thomas          spencer75@example.com  +57 4341305478            352 Joel Extension Suite 962, New Anthony, CO 33299        09-05-2024         Bronze  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           CO          57
          15             Laura Perez             sdavid@example.com +691 3193105560                1518 Green Locks Suite 348, New Brent, FM 51849        04-12-2024           Gold          504.0 3194.720000 2025-06-01 14:13:06           Beauty     Debit Card         Online           FM         691
          16           Erin Matthews            uhunter@example.net +972 4807803711                       67623 Morgan Hollow, Hillshire, IL 78665        12-11-2023         Bronze          531.0  322.340000 2025-04-05 11:19:25         Clothing     Debit Card    Los Angeles           IL         972
          16           Erin Matthews            uhunter@example.net +972 4807803711                       67623 Morgan Hollow, Hillshire, IL 78665        12-11-2023         Bronze          635.0  492.190000 2025-01-23 18:39:00         Clothing           Cash          Miami           IL         972
          17        Melissa Alvarado           parkjohn@example.net   +1 4118574974                                      USNS Austin, FPO AP 52643        24-06-2024           Gold          116.0  404.660000 2025-05-15 09:16:08             Home     Debit Card       New York           AP           1
          17        Melissa Alvarado           parkjohn@example.net   +1 4118574974                                      USNS Austin, FPO AP 52643        24-06-2024           Gold          374.0 2445.230000 2025-02-18 22:07:41             Home    Credit Card        Chicago           AP           1
          17        Melissa Alvarado           parkjohn@example.net   +1 4118574974                                      USNS Austin, FPO AP 52643        24-06-2024           Gold          681.0 4752.120000 2025-05-31 10:50:45           Sports           Cash          Miami           AP           1
          18         Mr. Ernest Dunn        kelseybrown@example.net   +1 6875437471            3112 Lydia Freeway Suite 927, South Susan, RI 11726        27-01-2025           Gold          570.0 2929.470000 2025-03-18 13:34:29           Beauty    Credit Card          Miami           RI           1
          19           David Johnson         marynelson@example.org +680 2444392274        992 Harris Pines Suite 049, North Marychester, PW 73177        21-02-2025         Silver            4.0 2532.550126 2025-04-30 15:26:23           Sports     Debit Card    Los Angeles           PW         680
          19           David Johnson         marynelson@example.org +680 2444392274        992 Harris Pines Suite 049, North Marychester, PW 73177        21-02-2025         Silver           99.0 4361.190000 2025-05-27 16:17:17      Electronics    Credit Card        Chicago           PW         680
          19           David Johnson         marynelson@example.org +680 2444392274        992 Harris Pines Suite 049, North Marychester, PW 73177        21-02-2025         Silver          546.0 1600.940000 2025-03-24 15:39:10           Beauty     Debit Card         Online           PW         680
          20           Wayne Morales          qwilliams@example.com   +1 8755593832                         15344 Hill Pike, Matthewport, FL 45434        22-02-2025           Gold          195.0  746.430000 2025-04-02 02:14:27             Home         PayPal          Miami           FL           1
          20           Wayne Morales          qwilliams@example.com   +1 8755593832                         15344 Hill Pike, Matthewport, FL 45434        22-02-2025           Gold          291.0 3402.300000 2025-03-24 02:17:33      Electronics         PayPal          Miami           FL           1
          20           Wayne Morales          qwilliams@example.com   +1 8755593832                         15344 Hill Pike, Matthewport, FL 45434        22-02-2025           Gold          874.0 3934.820000 2025-05-04 10:16:59           Sports    Credit Card         Online           FL           1
          21         Michael Vincent       jonesjeffrey@example.com   +1 6859354111                  455 Moore Orchard, New Richardhaven, RI 42023        13-06-2024         Silver          176.0 4674.530000 2025-02-25 15:55:18         Clothing    Credit Card          Miami           RI           1
          22            Tammie Mcgee          nsullivan@example.com +356 1768402659            6371 Long Path Apt. 940, South Anthonyton, MT 86683        24-10-2024         Silver          721.0  640.830000 2025-05-04 03:33:13           Sports           Cash    Los Angeles           MT         356
          23         Marisa Martinez              zward@example.org   +1 2216091291        5029 Wall Mountain Suite 847, New Chelseabury, IA 90393        29-03-2025         Bronze          442.0 1908.490000 2025-04-21 01:10:46           Beauty     Debit Card         Online           IA           1
          24        Crystal Peterson      taylorcharles@example.com   +1 4307111833                               Unit 5741 Box 1124, DPO AA 18219        07-08-2023         Bronze          133.0  979.810000 2025-06-13 05:19:21      Electronics         PayPal         Online           AA           1
          24        Crystal Peterson      taylorcharles@example.com   +1 4307111833                               Unit 5741 Box 1124, DPO AA 18219        07-08-2023         Bronze          141.0 1164.890000 2025-06-05 09:17:17         Clothing     Debit Card        Chicago           AA           1
          24        Crystal Peterson      taylorcharles@example.com   +1 4307111833                               Unit 5741 Box 1124, DPO AA 18219        07-08-2023         Bronze          717.0 4292.900000 2025-03-18 08:24:05             Home           Cash    Los Angeles           AA           1
          25        Jeremy Alexander         smithkevin@example.com   +1 1199699309                       1520 Reid Turnpike, Clarkville, CA 39102        13-06-2025         Silver          493.0  591.950000 2025-05-13 06:44:39           Beauty     Debit Card         Online           CA           1
          26            James Graham           chawkins@example.net +379 9976567695                         2809 Young Squares, Lisaside, VA 53732        10-03-2024           Gold          868.0 3378.580000 2025-04-27 11:24:04         Clothing     Debit Card    Los Angeles           VA         379
          27        William Morrison      browningdavid@example.org   +1 4866768923                 76577 Keith Falls, West Melissashire, NC 55275        01-08-2024           Gold          214.0 2887.520000 2025-05-15 08:47:35         Clothing     Debit Card        Chicago           NC           1
          27        William Morrison      browningdavid@example.org   +1 4866768923                 76577 Keith Falls, West Melissashire, NC 55275        01-08-2024           Gold          753.0 3558.590000 2025-04-25 08:18:22      Electronics         PayPal          Miami           NC           1
          27        William Morrison      browningdavid@example.org   +1 4866768923                 76577 Keith Falls, West Melissashire, NC 55275        01-08-2024           Gold          813.0 2468.380000 2025-05-16 04:49:59             Home         PayPal    Los Angeles           NC           1
          28            Brandon Hall       brandon hall@example.com  +57 9741233048               8143 Robert Cove Apt. 103, Sanchezport, CO 78231        07-04-2024           Gold          210.0 2404.430000 2025-05-11 16:03:42         Clothing    Credit Card        Chicago           CO          57
          29           Morgan Wilson         michelle12@example.net   +1 2584802466                          05880 Hudson Row, Jessefurt, KS 54128        04-11-2024         Silver  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           KS           1
          30            Heather Hill            qwillis@example.com +249 4424568115                     4339 Brown Crescent, Lambchester, SD 62832        15-12-2024         Silver          946.0 1252.530000 2025-06-01 10:04:29             Home           Cash          Miami           SD         249
          31           Louis Beasley             bjones@example.net   +1 2343113270              71975 Smith Drive Suite 746, Bairdmouth, MP 70886        18-09-2023         Bronze          905.0  258.160000 2025-05-28 23:35:33           Sports    Credit Card          Miami           MP           1
          32           Julie Shelton          ryanpatel@example.net   +1 3071035146                                       USNS Brown, FPO AP 55711        02-12-2024           Gold           70.0 1272.210000 2025-04-03 07:26:00           Sports     Debit Card          Miami           AP           1
          32           Julie Shelton          ryanpatel@example.net   +1 3071035146                                       USNS Brown, FPO AP 55711        02-12-2024           Gold          469.0 4664.710000 2025-05-06 10:40:47           Sports         PayPal    Los Angeles           AP           1
          33           Erin Stephens             kyle83@example.com  +57 6494438577                5911 Amy Creek Suite 329, Michaelside, CO 25722        02-08-2024         Silver          137.0 4934.620000 2025-03-28 19:03:18      Electronics           Cash         Online           CO          57
          33           Erin Stephens             kyle83@example.com  +57 6494438577                5911 Amy Creek Suite 329, Michaelside, CO 25722        02-08-2024         Silver          224.0 3477.450000 2025-05-29 09:29:52             Home    Credit Card       New York           CO          57
          34      Christopher Powers           nsimmons@example.com +355 3412772276                          27599 David Mews, Juliefort, AL 92098        09-06-2024         Silver          456.0 4270.260000 2025-04-21 20:03:33           Sports         PayPal        Chicago           AL         355
          34      Christopher Powers           nsimmons@example.com +355 3412772276                          27599 David Mews, Juliefort, AL 92098        09-06-2024         Silver          522.0 1037.020000 2025-04-13 01:06:52      Electronics    Credit Card        Chicago           AL         355
          35             Rachel Lang       huntcourtney@example.org   +1 3437768211                               PSC 5662, Box 7419, APO AA 70596        13-11-2024         Silver          130.0 3691.230000 2025-01-18 18:29:24             Home     Debit Card         Online           AA           1
          35             Rachel Lang       huntcourtney@example.org   +1 3437768211                               PSC 5662, Box 7419, APO AA 70596        13-11-2024         Silver          495.0 2947.590000 2025-04-25 16:52:12         Clothing    Credit Card       New York           AA           1
          35             Rachel Lang       huntcourtney@example.org   +1 3437768211                               PSC 5662, Box 7419, APO AA 70596        13-11-2024         Silver          593.0   73.200000 2025-06-10 03:55:57             Home     Debit Card       New York           AA           1
          36       Christopher Clark  christopher clark@example.com +356 1196093438        2325 Danielle Knolls Suite 719, Gabrielleview, MT 11649        13-01-2024           Gold          709.0  990.050000 2025-04-15 06:24:06         Clothing    Credit Card       New York           MT         356
          37           Jessica Hardy          cherylray@example.org +692 2448757801           8293 Martin Ridges Apt. 444, Lake Erikfort, MH 63270        13-08-2024           Gold          204.0 1944.720000 2025-02-03 17:50:58           Sports    Credit Card          Miami           MH         692
          38            Paul Collins      brittanychase@example.com   +1 9958207641         895 Anthony Lodge Suite 819, North Cassandra, TX 86555        05-07-2024         Bronze  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           TX           1
          39           Lauren Fisher           wesley32@example.net   +1 4695073423              9633 Victoria Loop Apt. 271, Hannahside, MS 96656        14-06-2025           Gold  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           MS           1
          40               Amy Gates            jesse14@example.org +373 8721983028            69324 Jennifer Plaza Apt. 905, Haroldview, MD 67322        24-11-2024           Gold          170.0 3335.280000 2025-05-03 06:40:34           Sports           Cash        Chicago           MD         373
          41         Breanna Elliott             mark59@example.net   +1 9845329433            29664 Lauren Mountain Apt. 243, West Mary, NV 57114        19-11-2024         Silver          265.0 2521.360000 2025-05-20 05:36:38      Electronics           Cash          Miami           NV           1
          41         Breanna Elliott             mark59@example.net   +1 9845329433            29664 Lauren Mountain Apt. 243, West Mary, NV 57114        19-11-2024         Silver          315.0 4539.880000 2025-04-19 02:29:56         Clothing     Debit Card          Miami           NV           1
          42       Mr. Andrew Austin          heather79@example.com   +1 7789181895                         200 Thomas Flat, South James, MP 96716        12-06-2025           Gold  Not Available 2532.550126       Not Available    Not Available  Not Available  Not Available           MP           1
          43            Kelsey Young        mckeeconnie@example.org   +1 2194201723               8806 Davis Fall Suite 188, East Brenda, WI 95051        04-12-2024           Gold          823.0  130.850000 2025-05-02 02:51:33           Sports         PayPal        Chicago           WI           1

In [87]:
dfnew.iloc[567]

customer_id                                                      410
name                                                 Rebecca Roberts
email                                              nhill@example.org
phone                                                  +1 7234854699
address              6414 Michael Trace, South Christopher, HI 58174
registration_date                                         20-10-2023
loyalty_status                                                Silver
transaction_id                                                 772.0
amount                                                       3895.36
transaction_date                                 2025-01-25 13:45:04
product_category                                              Sports
payment_method                                            Debit Card
store_location                                                Online
country_code                                                      HI
CallingCode                                                        1
Name: 567, dtype: object

In [89]:
##3

newdata = dfnew.loc[dfnew['amount'].astype(float) > dfnew['amount'].mean()]

In [ ]:

newdata1 = dfnew.loc[dfnew['amount'].astype(float) > 1000]

In [93]:
print(len(newdata))

482

In [94]:
newdata.head(5)

,customer_id,name,email,phone,address,registration_date,loyalty_status,transaction_id,amount,transaction_date,product_category,payment_method,store_location,country_code,CallingCode
0,1,Michelle Kidd,vayala@example.net,+971 6197234258,"USNS Santiago, FPO AE 80872",25-01-2025,Gold,8.0,2652.57,2025-04-19 14:46:00,Home,Credit Card,New York,AE,971
6,7,Louis Miller,patriciaelliott@example.org,+1 1988627105,"02590 Marshall Well, Sheppardland, CT 88067",30-09-2024,Gold,470.0,3241.66,2025-05-15 15:17:05,Electronics,PayPal,Los Angeles,CT,1
10,10,Rachel White,whitemichael@example.org,+972 4107299740,"6182 Brown Mountain, South Gary, IL 29016",25-02-2024,Bronze,173.0,3456.05,2025-04-15 19:26:48,Home,Debit Card,Online,IL,972
11,10,Rachel White,whitemichael@example.org,+972 4107299740,"6182 Brown Mountain, South Gary, IL 29016",25-02-2024,Bronze,548.0,2954.52,2025-05-21 22:54:54,Sports,Debit Card,Miami,IL,972
14,12,Christine Delgado,yfarrell@example.net,+1 3108349008,"PSC 4025, Box 2078, APO AA 61121",18-04-2024,Bronze,126.0,3696.64,2025-02-15 19:59:56,Beauty,Cash,Online,AA,1

In [97]:
dfnew.to_csv('C:\\Users\\Avi\\OneDrive - Kasmo Digital Private Limited\\Desktop\\Python_tutorial1\\final_output.csv', index=False)